include: '/.gitlab/_common.gitlab-ci.yml'

image: ${CI_RENOVATE_IMAGE}

variables:
  CI_RENOVATE_IMAGE: renovate/renovate:35.8.2@sha256:062dfcdb3db7ee6c5ff13504caa10db65b7d19e07c10aa2d22f77879e74e7721
