import { defineStore } from 'pinia';
import { Theme } from '../theme';

export type TDeviceStore = {
	homeProfile: string,
	mobileHomeProfile: string,
	deckProfile: string,
	deckMode: boolean,
	deckColumnAlign: string,
	deckColumnWidth: string,
	useBlur: boolean,
	useShadow: boolean,
	deckTemporaryColumnPosition: string,
	deckTemporaryColumnIndex: number,
	roundedCorners: boolean,
	reduceMotion: boolean,
	darkmode: boolean,
	darkTheme: string,
	lightTheme: string,
	lineWidth: number,
	fontSize: number,
	themes: Theme[],
	enableSounds: boolean,
	enableSoundsInTimeline: boolean,
	enableSoundsInNotifications: boolean,
	//soundVolume: 0.5,
	mediaVolume: number,
	enableQueueJammed: boolean,
	enableSpeech: boolean,
	lang: null,
	appTypeForce: string,
	debug: boolean,
	showAdvancedSettings: boolean,
	lightmode: boolean,
	loadRawImages: boolean,
	alwaysShowNsfw: boolean,
	postStyle: string,
	navbar: string,
	mobileNotificationPosition: string,
	useOsDefaultEmojis: boolean,
	disableShowingAnimatedImages: boolean,
	useAbsoluteTime: boolean,
	expandUsersPhotos: boolean,
	expandUsersActivity: boolean,
	showPostPreview: boolean,
	enableMobileQuickNotificationView: boolean,
	instanceTicker: string, // none, remote, always
	hasDisconnectedAction: string, // nothing, notify, reload
	roomGraphicsQuality: string,
	roomUseOrthographicCamera: boolean,
	activeEmojiCategoryName: undefined,
	recentEmojis: [],
}

export const useDeviceStore = defineStore('device', {
	state: () => ({
		homeProfile: 'Default',
		mobileHomeProfile: 'Default',
		deckProfile: 'Default',
		deckMode: false,
		deckColumnAlign: 'center',
		deckColumnWidth: 'normal',
		useBlur: true,
		useShadow: true,
		deckTemporaryColumnPosition: 'right',
		deckTemporaryColumnIndex: 1,
		roundedCorners: true,
		reduceMotion: false,
		darkmode: true,
		darkTheme: 'dark',
		lightTheme: 'light',
		lineWidth: 1,
		fontSize: 0,
		themes: [] as Theme[],
		enableSounds: true,
		enableSoundsInTimeline: true,
		enableSoundsInNotifications: true,
		//soundVolume: 0.5,
		mediaVolume: 0.5,
		enableQueueJammed: false,
		enableSpeech: false,
		lang: null,
		appTypeForce: 'auto',
		debug: false,
		showAdvancedSettings: false,
		lightmode: false,
		loadRawImages: false,
		alwaysShowNsfw: false,
		postStyle: 'standard',
		navbar: 'top',
		mobileNotificationPosition: 'bottom',
		useOsDefaultEmojis: false,
		disableShowingAnimatedImages: false,
		useAbsoluteTime: false,
		expandUsersPhotos: true,
		expandUsersActivity: true,
		showPostPreview: true,
		enableMobileQuickNotificationView: false,
		instanceTicker: 'remote', // none, remote, always
		hasDisconnectedAction: 'notify', // nothing, notify, reload
		roomGraphicsQuality: 'medium',
		roomUseOrthographicCamera: true,
		activeEmojiCategoryName: undefined,
		recentEmojis: [],
	}),
	persist: true,
});
