import { defineStore } from 'pinia';
import { Theme } from '../theme';

export const useDeviceStore = defineStore('device', {
	state: () => ({
		homeProfile: 'Default',
		mobileHomeProfile: 'Default',
		deckProfile: 'Default',
		deckMode: false,
		deckColumnAlign: 'center',
		deckColumnWidth: 'normal',
		useBlur: true,
		useShadow: true,
		deckTemporaryColumnPosition: 'right',
		deckTemporaryColumnIndex: 1,
		roundedCorners: true,
		reduceMotion: false,
		darkmode: true,
		darkTheme: 'dark',
		lightTheme: 'light',
		lineWidth: 1,
		fontSize: 0,
		themes: [] as Theme[],
		enableSounds: true,
		enableSoundsInTimeline: true,
		enableSoundsInNotifications: true,
		//soundVolume: 0.5,
		mediaVolume: 0.5,
		enableQueueJammed: false,
		enableSpeech: false,
		lang: null,
		appTypeForce: 'auto',
		debug: false,
		showAdvancedSettings: false,
		lightmode: false,
		loadRawImages: false,
		alwaysShowNsfw: false,
		postStyle: 'standard',
		navbar: 'top',
		mobileNotificationPosition: 'bottom',
		useOsDefaultEmojis: false,
		disableShowingAnimatedImages: false,
		useAbsoluteTime: false,
		expandUsersPhotos: true,
		expandUsersActivity: true,
		showPostPreview: true,
		enableMobileQuickNotificationView: false,
		instanceTicker: 'remote', // none, remote, always
		hasDisconnectedAction: 'notify', // nothing, notify, reload
		roomGraphicsQuality: 'medium',
		roomUseOrthographicCamera: true,
		activeEmojiCategoryName: undefined,
		recentEmojis: [],
	}),
	persist: true,
});
