import { defineStore } from 'pinia';

export const useSettingsStore = defineStore('settings', {
	state: () => ({
		keepCw: false,
		tagTimelines: [],
		fetchOnScroll: true,
		remainDeletedNote: false,
		showPostFormOnTopOfTl: false,
		suggestRecentHashtags: true,
		showClockOnHeader: true,
		circleIcons: true,
		contrastedAcct: true,
		showFullAcct: false,
		showVia: true,
		showReplyTarget: true,
		showMyRenotes: true,
		showRenotedMyNotes: true,
		showLocalRenotes: true,
		loadRemoteMedia: true,
		disableViaMobile: false,
		memo: null,
		iLikeSushi: false,
		rememberNoteVisibility: false,
		defaultNoteVisibility: 'public',
		wallpaper: null,
		webSearchEngine: 'https://www.google.com/?#q={{query}}',
		mutedWords: [],
		gamesReversiShowBoardLabels: false,
		gamesReversiUseAvatarStones: true,
		disableAnimatedMfm: false,
		homeProfiles: {},
		mobileHomeProfiles: {},
		deckProfiles: {},
		uploadFolder: null,
		pastedFileName: 'yyyy-MM-dd HH-mm-ss [{{number}}]',
		pasteDialog: false,
		reactions: [
			'like',
			'love',
			'laugh',
			'hmm',
			'surprise',
			'congrats',
			'angry',
			'confused',
			'rip',
			'pudding',
		],
	}),
	persist: true,
});
