import Vue from 'vue';

import dummy from './dummy.vue';
import userName from './user-name.vue';
import followButton from './follow-button.vue';
import error from './error.vue';
import noteSkeleton from './note-skeleton.vue';
import instance from './instance.vue';
import cwButton from './cw-button.vue';
import tagCloud from './tag-cloud.vue';
import trends from './trends.vue';
import analogClock from './analog-clock.vue';
import menu from './menu.vue';
import noteHeader from './note-header.vue';
import renote from './renote.vue';
import signin from './signin.vue';
import signup from './signup.vue';
import forkit from './forkit.vue';
import acct from './acct.vue';
import avatar from './avatar.vue';
import nav from './nav.vue';
import misskeyFlavoredMarkdown from './misskey-flavored-markdown.vue';
import poll from './poll.vue';
import reactionIcon from './reaction-icon.vue';
import reactionsViewer from './reactions-viewer.vue';
import time from './time.vue';
import mediaList from './media-list.vue';
import uploader from './uploader.vue';
import streamIndicator from './stream-indicator.vue';
import ellipsis from './ellipsis.vue';
import urlPreview from './url-preview.vue';
import fileTypeIcon from './file-type-icon.vue';
import emoji from './emoji.vue';
import welcomeTimeline from './welcome-timeline.vue';
import userList from './user-list.vue';
import frac from './frac.vue';
import uiInput from './ui/input.vue';
import uiButton from './ui/button.vue';
import uiHorizonGroup from './ui/horizon-group.vue';
import uiCard from './ui/card.vue';
import uiForm from './ui/form.vue';
import uiTextarea from './ui/textarea.vue';
import uiSwitch from './ui/switch.vue';
import uiRadio from './ui/radio.vue';
import uiSelect from './ui/select.vue';
import uiInfo from './ui/info.vue';
import uiMargin from './ui/margin.vue';
import uiHr from './ui/hr.vue';
import uiPagination from './ui/pagination.vue';
import uiModal from './ui/modal.vue';
import formButton from './ui/form/button.vue';
import formRadio from './ui/form/radio.vue';

Vue.component('Mfm', misskeyFlavoredMarkdown);
Vue.component('MkDummy', dummy);
Vue.component('MkUserName', userName);
Vue.component('MkFollowButton', followButton);
Vue.component('MkError', error);
Vue.component('MkNoteSkeleton', noteSkeleton);
Vue.component('MkInstance', instance);
Vue.component('MkCwButton', cwButton);
Vue.component('MkTagCloud', tagCloud);
Vue.component('MkTrends', trends);
Vue.component('MkAnalogClock', analogClock);
Vue.component('MkMenu', menu);
Vue.component('MkNoteHeader', noteHeader);
Vue.component('MkRenote', renote);
Vue.component('MkSignin', signin);
Vue.component('MkSignup', signup);
Vue.component('MkForkit', forkit);
Vue.component('MkAcct', acct);
Vue.component('MkAvatar', avatar);
Vue.component('MkNav', nav);
Vue.component('MkPoll', poll);
Vue.component('MkReactionIcon', reactionIcon);
Vue.component('MkReactionsViewer', reactionsViewer);
Vue.component('MkTime', time);
Vue.component('MkMediaList', mediaList);
Vue.component('MkUploader', uploader);
Vue.component('MkStreamIndicator', streamIndicator);
Vue.component('MkEllipsis', ellipsis);
Vue.component('MkUrlPreview', urlPreview);
Vue.component('MkFileTypeIcon', fileTypeIcon);
Vue.component('MkEmoji', emoji);
Vue.component('MkWelcomeTimeline', welcomeTimeline);
Vue.component('MkUserList', userList);
Vue.component('MkFrac', frac);
Vue.component('UiInput', uiInput);
Vue.component('UiButton', uiButton);
Vue.component('UiHorizonGroup', uiHorizonGroup);
Vue.component('UiCard', uiCard);
Vue.component('UiForm', uiForm);
Vue.component('UiTextarea', uiTextarea);
Vue.component('UiSwitch', uiSwitch);
Vue.component('UiRadio', uiRadio);
Vue.component('UiSelect', uiSelect);
Vue.component('UiInfo', uiInfo);
Vue.component('UiMargin', uiMargin);
Vue.component('UiHr', uiHr);
Vue.component('UiPagination', uiPagination);
Vue.component('UiModal', uiModal);
Vue.component('FormButton', formButton);
Vue.component('FormRadio', formRadio);
