import { App } from 'vue';

import dummy from './dummy.vue';
import userName from './user-name.vue';
import followButton from './follow-button.vue';
import error from './error.vue';
import noteSkeleton from './note-skeleton.vue';
import instance from './instance.vue';
import cwButton from './cw-button.vue';
import tagCloud from './tag-cloud.vue';
import trends from './trends.vue';
import analogClock from './analog-clock.vue';
import menu from './menu.vue';
import noteHeader from './note-header.vue';
import renote from './renote.vue';
import signin from './signin.vue';
import signup from './signup.vue';
import reminder from './reminder.vue';
import forkit from './forkit.vue';
import acct from './acct.vue';
import avatar from './avatar.vue';
import nav from './nav.vue';
import misskeyFlavoredMarkdown from './misskey-flavored-markdown.vue';
import poll from './poll.vue';
import reactionIcon from './reaction-icon.vue';
import reactionsViewer from './reactions-viewer.vue';
import time from './time.vue';
import mediaList from './media-list.vue';
import uploader from './uploader.vue';
import streamIndicator from './stream-indicator.vue';
import ellipsis from './ellipsis.vue';
import urlPreview from './url-preview.vue';
import fileTypeIcon from './file-type-icon.vue';
import emoji from './emoji.vue';
import welcomeTimeline from './welcome-timeline.vue';
import userList from './user-list.vue';
import frac from './frac.vue';
import uiInput from './ui/input.vue';
import uiButton from './ui/button.vue';
import uiHorizonGroup from './ui/horizon-group.vue';
import uiCard from './ui/card.vue';
import uiForm from './ui/form.vue';
import uiTextarea from './ui/textarea.vue';
import uiSwitch from './ui/switch.vue';
import uiRadio from './ui/radio.vue';
import uiSelect from './ui/select.vue';
import uiInfo from './ui/info.vue';
import uiMargin from './ui/margin.vue';
import uiHr from './ui/hr.vue';
import uiPagination from './ui/pagination.vue';
import uiModal from './ui/modal.vue';
import formButton from './ui/form/button.vue';
import formRadio from './ui/form/radio.vue';

export default function(app: App) {
	app.component('Mfm', misskeyFlavoredMarkdown);
	app.component('MkDummy', dummy);
	app.component('MkUserName', userName);
	app.component('MkFollowButton', followButton);
	app.component('MkError', error);
	app.component('MkNoteSkeleton', noteSkeleton);
	app.component('MkInstance', instance);
	app.component('MkCwButton', cwButton);
	app.component('MkTagCloud', tagCloud);
	app.component('MkTrends', trends);
	app.component('MkAnalogClock', analogClock);
	app.component('MkMenu', menu);
	app.component('MkNoteHeader', noteHeader);
	app.component('MkRenote', renote);
	app.component('MkSignin', signin);
	app.component('MkSignup', signup);
	app.component('MkReminder', reminder);
	app.component('MkForkit', forkit);
	app.component('MkAcct', acct);
	app.component('MkAvatar', avatar);
	app.component('MkNav', nav);
	app.component('MkPoll', poll);
	app.component('MkReactionIcon', reactionIcon);
	app.component('MkReactionsViewer', reactionsViewer);
	app.component('MkTime', time);
	app.component('MkMediaList', mediaList);
	app.component('MkUploader', uploader);
	app.component('MkStreamIndicator', streamIndicator);
	app.component('MkEllipsis', ellipsis);
	app.component('MkUrlPreview', urlPreview);
	app.component('MkFileTypeIcon', fileTypeIcon);
	app.component('MkEmoji', emoji);
	app.component('MkWelcomeTimeline', welcomeTimeline);
	app.component('MkUserList', userList);
	app.component('MkFrac', frac);
	app.component('UiInput', uiInput);
	app.component('UiButton', uiButton);
	app.component('UiHorizonGroup', uiHorizonGroup);
	app.component('UiCard', uiCard);
	app.component('UiForm', uiForm);
	app.component('UiTextarea', uiTextarea);
	app.component('UiSwitch', uiSwitch);
	app.component('UiRadio', uiRadio);
	app.component('UiSelect', uiSelect);
	app.component('UiInfo', uiInfo);
	app.component('UiMargin', uiMargin);
	app.component('UiHr', uiHr);
	app.component('UiPagination', uiPagination);
	app.component('UiModal', uiModal);
	app.component('FormButton', formButton);
	app.component('FormRadio', formRadio);
}
