import Vue from 'vue';

import wAnalogClock from './analog-clock.vue';
import wVersion from './version.vue';
import wRss from './rss.vue';
import wServer from './server.vue';
import wPostsMonitor from './posts-monitor.vue';
import wMemo from './memo.vue';
import wBroadcast from './broadcast.vue';
import wCalendar from './calendar.vue';
import wPhotoStream from './photo-stream.vue';
import wSlideshow from './slideshow.vue';
import wTips from './tips.vue';
import wNav from './nav.vue';
import wHashtags from './hashtags.vue';
import wInstance from './instance.vue';
import wPostForm from './post-form.vue';

Vue.component('MkwAnalogClock', wAnalogClock);
Vue.component('MkwNav', wNav);
Vue.component('MkwCalendar', wCalendar);
Vue.component('MkwPhotoStream', wPhotoStream);
Vue.component('MkwSlideshow', wSlideshow);
Vue.component('MkwTips', wTips);
Vue.component('MkwBroadcast', wBroadcast);
Vue.component('MkwServer', wServer);
Vue.component('MkwPostsMonitor', wPostsMonitor);
Vue.component('MkwMemo', wMemo);
Vue.component('MkwRss', wRss);
Vue.component('MkwVersion', wVersion);
Vue.component('MkwHashtags', wHashtags);
Vue.component('MkwInstance', wInstance);
Vue.component('MkwPostForm', wPostForm);
Vue.component('MkwQueue', () => import('./queue.vue').then(m => m.default));
Vue.component('MkwJobQueue', () => import('./job-queue.vue').then(m => m.default));
Vue.component('MkwAichan', () => import('./aichan.vue').then(m => m.default));
